name: Plugin asset/readme update
on:
  push:
    branches:
      - main
jobs:
  trunk:
    name: Update wp.org assets and readme.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{secrets.SLUG}}
          IGNORE_OTHER_FILES: true
